name: Pheonix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: #Set the CRON for MIDNIGHT IST ---> UTC
    - cron: "30 18 * * *"
  workflow_dispatch:
      inputs:
        env:
          description: "Environment"
          type: choice
          options: [qa,uat,dev]
          default: qa
          required: true
        suiteXmlFile:
          description: "TestNG xml files"
          type: choice
          options: [testng.xml,smoke.xml,sanity.xml]
          default: testng.xml
          required: true  

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute Test Automation Framework
      run: mvn clean test -DsuiteXmlFile=${{ github.event.inputs.suiteXmlFile }} -Denv="${{ github.event.inputs.env }}"

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: SureFire Report
        path: target/surefire-reports/
        retention-days: 10
        


