name: Pheonix Test Automation Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 22
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
        
    - name: Execute Test Automation Framework
      run: mvn clean test -DsuiteXmlFile=testng.xml -Denv=qa

    - name: Upload a Build Artifact
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: SureFire Report
        path: target/surefire-reports/
        retention-days: 10
        


